openapi: 3.0.1
info:
  version: 1.0.0
  title: School Api
  description: Es un endpoint para iniciar seccion para obtener token, registrar usuarios, materias y modificar sus datos.
  contact:
      name: Eduardo Avila
      email: eduardoavilach@hotmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost/apiSchool/public/api/
    description: Direccion de servidor Api Local
security:
  - bearerAuth: []